### ISSUE TITLE
find out and describe a workflow for making a repo clone on Windows

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/collab-demos#17]
[https://desktop.github.com/](https://desktop.github.com/) maybe

**Comment by jspaaks** [comment]
Done. @sbranchett would you review [this](../blob/master/doc/installing-github-desktop-on-windows.md) document, see if it works for you.

**Comment by ghost** [comment]
Wow, it worked! I was using my PC at home which didn't yet have anything Git on it.
Step 7 reads
7.Select  collab-demos
You should maybe add 'and click on the tick mark at the bottom'.
I had to do this 3 times to get it working, but it did work. Took 2 hours.

Just what I needed as a back-up plan. Thanks

**Comment by jspaaks** [comment]
Done. Out of interest, why 3 times?

**Comment by ghost** [comment]
Kon de server niet contacten en kon iets niet downloaden.
Misschien mijn internet verbinding, misschien door initialisatie omdat het de eerste keer was.
Groeten,
Susan
