### ISSUE TITLE
figure does not represent the most used type of MS

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/collab-demos#83]
Er zijn verschillende ontwerpen van mass spectrometers, die van de figuur is één van de opties (en in de praktijk niet de meest gebruikte/succesvolle).

**Comment by ridderl** [comment]
The figure is fine, I just changed the text a bit to indicate it is not the only possible design of mass spectrometry ....

**Comment by jspaaks** [comment]
I think I just removed the line in question, but I don;t think it's a problem for the reader's understanding of the concept. It's almost a given that there are different designs.
