### ISSUE TITLE
atomic weights are off in figures

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/collab-demos#84]
Een atomen bestaan in verschillende isotopen, die je afzonderlijk meet in de MS. Dus het gewicht (atomic weight) van koolstof is 12.01, maar de massa van de meest voorkomende isotoop is 12.0000. Waar komen de figuren van de spectra vandaan? Ik zou zeggen dat de massa’s niet helemaal kloppen. De “exact mass” van methaan is nl. 16.03, niet 16.04. (Dit is voor accurate MS een groot verschil, die meten to de 4e decimaal nauwkeurig.)

**Comment by jspaaks** [comment]
I got the masses from Google, e.g.
- [methane: 16.04](https://www.google.nl/search?q=molecular+mass+methane)
- [carbon: 12.01](https://www.google.nl/search?q=molecular+mass+carbon)

but I did notice some differences in the numbers between these numbers and some MS figures I found. Is that because the google numbers are a weighted average of different isotopes (weighted by abundance)? 98.93% carbon-12 + 1.109% carbon-13 = 0.9893 \* 12 + 0.0109 \* 13.003355 = 12.01 ? (numbers from wikipedia this time, using `isotope mass` of carbon-12 and carbon-13, respectively)

So in the figures, I would need to assume carbon-12 and hydrogen-1 isotopes only, until the effect of different isotopes is introduced later on in the text.

That means for 
- methane CH4:  1 \* 12 + 4 \* 1.00782504 = 16.03130
- CH2: 1 \* 12 + 2 \* 1.00782504 = 14.0156
- H2: 2 \* 1.00782504 = 2.0157

Additionally, I think I'm right in saying that CH2 and H2 are not stable, they form new compounds with different masses, so you wouldn't see 14.0156 and 2.0157 in the spectrogram, correct?

**Comment by ridderl** [comment]
The new masses you calculate are almost correct and **good enough for the current intro**. The ions also have an electron extra, or less (depending of the ionisation mode; positive or negative). Electron mass starts to play a role in accurate mass spectrometry :-)

**Comment by ridderl** [comment]
I'm not entirely sure about the methane fragmentation spectrum. 

Maybe the mass spectrum of CO2 is a nice and easier one to illustrate:
[http://www.massbank.jp/jsp/Dispatcher.jsp?type=disp&id=JP001576&site=10](http://www.massbank.jp/jsp/Dispatcher.jsp?type=disp&id=JP001576&site=10)

It is quite easy to explain the peaks ...

**Comment by jspaaks** [comment]
Agree. I'll update the figures and text with these numbers:
  12 5.35 54
  16 9.25 93
  22 1.75 18
  28 12.67 127
  44 99.99 999
  45 1.27 13

**Comment by jspaaks** [comment]
so the png looks like this:
![mass-spectrum-co2](https://cloud.githubusercontent.com/assets/4558105/14491233/f43829f8-0177-11e6-8df2-0a67c261ee90.png)
what do you think? (I've used integers for the masses, as per the example you suggested)

**Comment by jspaaks** [comment]
explanation of the masses (all in their most abundant isotope configuration except mass at 45):
- 12: C atom
- 16: O atom
- 22: double charged CO2
- 28: CO
- 44: CO2
- 45: CO2 with 13-carbon instead of 12-carbon

**update** found an explanantion [here](http://www.ms-textbook.com/1st/chap_1/a/a1_2.html)

**Comment by ridderl** [comment]
Excellent
