### ISSUE TITLE
Add story line for green tea example

### ISSUE THREAD

**Issue by ridderl** [NLeSC/collab-demos#89]

**Comment by jspaaks** [comment]
Maybe we can combine this with the screencast (which I still have to make). You can then see the mouse move, pointing out different things in the interface, and we can then use subtitles for the narrative. I've already written [a Python program](https://github.com/NLeSC/collab-demos/blob/master/src/jsontosrt.py) that generates the subtitles from JSON.

**Comment by ridderl** [comment]
I added a story line to the README, let me know what you think ....

**Comment by jspaaks** [comment]
Looks good. We're finally making real progress on this, yay!

**Comment by ridderl** [comment]
OK, we could use the given storyline to make the screencast as well. I can give it a try this afternoon ...

**Comment by jspaaks** [comment]
Perhaps it's easier to make a PPT presentation using fullscreen screenshots first. You can then easily overlay decorations like a rectangle to identify a widget, arrows to point out some details, or text labels to clarify something. Later on, we can then record the presentation and add subtitles if we want.

I understand you wanna go with the demo as-is?

**Comment by ridderl** [comment]
Well, if there is a bit more time, we could look into another compound (epigallocatechin gallate). See my additions to the story line...
Do you think that is a useful extension?

**Comment by jspaaks** [comment]
I still have to look at the recent addition to the storyline, so I don;t know yet. But what I meant by "going with the demo as-is" was, do you want to fix some of the easier-to-fix issues first (#65, #67, #69, #71, #73, #79, #91, #66, #68, #76, #78, #90)?
