### ISSUE TITLE
how do you upload chromatography data?

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/collab-demos#90]
[the widget](http://www.emetabolomics.org/magma) suggests that you can upload MS data only. Does this (implicitly) also mean chromatography data? Then maybe we should change some of the text labels to, e.g., LC/MS data

**Comment by ridderl** [comment]
??? There is an entry field below "format" ....

**Comment by ridderl** [comment]
Ah, now I get your point. Yes it is actually LC-MS/MS data you can upload.
Some of your points should become issues in the MAGMa github, not here ...

**Comment by jspaaks** [comment]
You're right about location of issues. Not sure what to do about it at the moment besides the obvious, i.e. migration of some of the issues.

**Comment by ridderl** [comment]
I will take care of this ...

**Comment by jspaaks** [comment]
FYI I made a pull request at [NLeSC/MAGMa #252](https://github.com/NLeSC/MAGMa/issues/252)
