### ISSUE TITLE
generate status table periodically

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/collab-demos#93]
let [this](https://github.com/NLeSC/collab-demos) readme be created evey hour by Jenkins using [this](https://github.com/NLeSC/collab-demos/blob/master/src/makereadme.py) Python script. Ask @sverhoeven for help...again

**Comment by sverhoeven** [comment]
You can trigger a nightly Travis-CI build using https://nightli.es/

See https://github.com/3D-e-Chem/3D-e-Chem.github.io/blob/master/BUILD_NIGHTLY.md how to perform git push during build.

**Comment by jspaaks** [comment]
All set up and done. README should now be automatically generated every night.
